version: "3.8"
services:
  radarr-extractor:
    image: crzyc/radarr-extractor:latest
    container_name: radarr-extractor
    environment:
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-/downloads}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "9898:9898"
    volumes:
      - ${DOWNLOAD_VOLUME}:/downloads
    restart: unless-stopped
    networks:
      - radarr_radarr_network

networks:
  radarr_radarr_network:
    external: true  # Using existing Radarr network